palette = "dsdm"

format = '''$username[ : ](bg:lightbg)$directory$character'''

add_newline = false

right_format = '$nix_shell$git_commit'

[username]
format = '[ $user ]($style)'
style_user = 'yellow bg:darkbg'
show_always = true

[status]
format = '[exit code $status ]($style)'
style = 'comment'
disabled = false

[cmd_duration]
format = '[in $duration]($style)'
style = 'comment'
min_time = 0
show_notifications = true
show_milliseconds = true
disabled = false

[character]
success_symbol = ''
error_symbol = ''

[directory]
truncation_length = 2
truncation_symbol = ''
format = '[$read_only]($read_only_style)[ $path ]($style)'
style = 'blue bg:darkbg'
read_only = " READONLY:"
read_only_style = 'red bg:darkbg'

[git_branch]
always_show_remote = true
format = ' $remote_name:$branch '
style = 'bold purple'
symbol = ''
disabled = false

[git_commit]
commit_hash_length = 7
format = '[$hash]($style)'
style = 'purple'
only_detached = false
disabled = false

[nix_shell]
symbol = "ïŒ“"

[palettes.dsdm]
background	= "!( global.colors.background )!"
darkbg		= "!( global.colors.darkbg )!"
lightbg		= "!( global.colors.lightbg )!"
foreground	= "!( global.colors.foreground )!"
lightfg		= "!( global.colors.lightfg )!"
darkfg		= "!( global.colors.darkfg )!"
black		= "!( global.colors.black )!"
red		= "!( global.colors.red )!"
green		= "!( global.colors.green )!"
yellow		= "!( global.colors.yellow )!"
blue		= "!( global.colors.blue )!"
magenta		= "!( global.colors.magenta )!"
cyan		= "!( global.colors.cyan )!"
white		= "!( global.colors.white )!"