palette = "dsdm"

format = '''$username[ : ](bg:lightbg)$directory$character'''

add_newline = false

right_format = '$nix_shell$git_commit'

[username]
format = '[ $user ]($style)'
style_user = 'yellow bg:darkbg'
show_always = true

[status]
format = '[exit code $status ]($style)'
style = 'comment'
disabled = false

[cmd_duration]
format = '[in $duration]($style)'
style = 'comment'
min_time = 0
show_notifications = true
show_milliseconds = true
disabled = false

[character]
success_symbol = ''
error_symbol = ''

[directory]
truncation_length = 2
truncation_symbol = ''
format = '[$read_only]($read_only_style)[ $path ]($style)'
style = 'blue bg:darkbg'
read_only = " READONLY:"
read_only_style = 'red bg:darkbg'

[git_branch]
always_show_remote = true
format = ' $remote_name:$branch '
style = 'bold purple'
symbol = ''
disabled = false

[git_commit]
commit_hash_length = 7
format = '[$hash]($style)'
style = 'purple'
only_detached = false
disabled = false

[nix_shell]
symbol = "ïŒ“"

[palettes.dsdm]
background	=	 "#1d2021"
darkbg		=	 "#141617"
lightbg		=	 "#282828"
foreground	=	 "#ebdbb2"
lightfg		=	 "#fbf1c7"
darkfg		=	 "#a89984"
black		=	 "#1d2021"
red		=        "#fb4934"
green		=	 "#b8bb26"
yellow		=	 "#fabd2f"
blue		=	 "#83a598"
magenta		=	 "#d3869b"
cyan		=	 "#8ec07c"
white		=	 "#ebdbb2"
